### ISSUE TITLE
Not Possible to change sigh SowMark0

### ISSUE THREAD

**Issue by sittim** [jacquesbh/vim-showmarks#1]
![selection_014](https://cloud.githubusercontent.com/assets/8825037/20729672/0c953502-b651-11e6-9020-3d7dad4cfa72.png)

Getting an error above, can you help?

**Comment by nic0-lab** [comment]
Hello, I had the same problem and I resolved it with this : 
Replaced the following line in showmarks.vim :
   ` exe 'sign place '.id.' name=ShowMark'.nm.' line='.ln.' buffer='.winbufnr(0)`
  by the following three lines

```
if ln > 0 " conditional which tests for the line number as greater than 0
    exe 'sign place '.id.' name=ShowMark'.nm.' line='.ln.' buffer='.winbufnr(0)
endif     " end conditional 
```

Found here in Google Groups : https://groups.google.com/forum/#!topic/vim_use/i_FRMtA5R60
