### ISSUE TITLE
How to enable at startup? 

### ISSUE THREAD

**Issue by eduardoarandah** [jacquesbh/vim-showmarks#2]
Might be a silly question, but.. 
how to enable at startup? 

This in my .vimrc don't work:

```
DoShowMarks
:DoShowMarks<CR>
exec DoShowMarks
```

**Comment by boring10** [comment]
You can place the following in your vimrc. It worked for me
`autocmd VimEnter * DoShowMarks`

Source: <https://stackoverflow.com/a/6821698/12066662>
