### ISSUE TITLE
How to refresh after new mark creation?

### ISSUE THREAD

**Issue by Xunius** [jacquesbh/vim-showmarks#3]
Hi,
Thanks for creating this tool.
Is there a way to refresh the mark signs after a new mark is added, e.g. when I have toggled `DoShowMarks`, then I added a new one `me`, how to somehow call `DoShowMarks` again so that this mark `e` is shown?

**Comment by jacquesbh** [comment]
I guess yes!

I don't maintain this project, it's a clone from https://www.vim.org/scripts/script.php?script_id=2142.
